-- database: ../test.sqlite
-- Note: Do not delete the line above! It is helpful for testing your init.sql file.
--
-- Drop existing tables to ensure a clean slate for database initialization
-- This allows the script to be run multiple times without conflicts
DROP TABLE IF EXISTS "restaurants";

-- Restaurants table: stores information about each restaurant in the catalog
-- name: unique restaurant name
-- address: physical location (must be unique)
-- rating: customer rating on a scale (typically 1-5)
-- avg_price: average price per meal in dollars
-- description: brief description of the restaurant's cuisine and atmosphere
-- file_ext: file extension for the restaurant's image (e.g., 'png', 'jpg')
CREATE TABLE "restaurants" (
    "id" INTEGER NOT NULL UNIQUE,
    "name" TEXT UNIQUE NOT NULL,
    "address" TEXT UNIQUE NOT NULL,
    "rating" INTEGER,
    "avg_price" INTEGER,
    "description" TEXT,
    "file_ext" TEXT NOT NULL,
    PRIMARY KEY ("id" AUTOINCREMENT)
);

DROP TABLE IF EXISTS "users";

-- Users table: stores admin user credentials
-- username: unique username for login
-- password: hashed password for security (using bcrypt)
CREATE TABLE "users" (
    "id" INTEGER NOT NULL UNIQUE,
    "username" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    PRIMARY KEY ("id" AUTOINCREMENT)
);

DROP TABLE IF EXISTS "sessions";

-- Sessions table: tracks active user sessions for authentication
-- user_id: foreign key reference to the logged-in user
-- session: unique session token for identifying user sessions
-- last_login: timestamp of the user's last login activity
CREATE TABLE "sessions" (
    "id" INTEGER NOT NULL UNIQUE,
    "user_id" INTEGER NOT NULL,
    "session" TEXT NOT NULL UNIQUE,
    "last_login" TEXT NOT NULL,
    PRIMARY KEY ("id" AUTOINCREMENT),
    FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);

DROP TABLE IF EXISTS "tags";

-- Tags table: stores all available tags for categorizing restaurants
-- Tags include cuisine types, dietary options, and price ranges
CREATE TABLE "tags" (
    "id" INTEGER NOT NULL UNIQUE,
    "name" TEXT NOT NULL,
    PRIMARY KEY ("id" AUTOINCREMENT)
);

DROP TABLE IF EXISTS "restaurant_tags";

-- Restaurant_tags table: junction table linking restaurants to their tags
-- Enables many-to-many relationship between restaurants and tags
-- restaurant_id: foreign key to restaurants table
-- tag_id: foreign key to tags table
CREATE TABLE "restaurant_tags" (
    "id" INTEGER NOT NULL UNIQUE,
    "restaurant_id" INTEGER NOT NULL,
    "tag_id" INTEGER NOT NULL,
    PRIMARY KEY ("id" AUTOINCREMENT),
    FOREIGN KEY ("restaurant_id") REFERENCES "restaurants" ("id"),
    FOREIGN KEY ("tag_id") REFERENCES "tags" ("id")
);

-- Seed data for valid users and corresponding passwords
-- Password is hashed using bcrypt ($2y$10$ indicates bcrypt algorithm)
-- Default admin password: 'monkey' (should be changed in production)
INSERT INTO
    users (username, password)
VALUES
    (
        'admin',
        '$2y$10$QtCybkpkzh7x5VN11APHned4J8fu78.eFXlyAMmahuAaNcbwZ7FH.'
    );

-- Note: seed data below are just placeholders generated by ChatGPT 5; it would be nice to have real/inspired places
-- tags table consists of a list of cuisine types,
/* several ideas to consider: dietary options, michelin-rated, price range
 Dietary Options: Vegan, Halal, Gluten-Free, Kosher
 Price Range: Affordable, Mid-Price, Fine-Dining */
-- Seed data for tags
-- Tags are used to categorize restaurants by cuisine type, dietary options, and price range
INSERT INTO
    "tags" ("name")
VALUES
    -- tags for cuisine type
    ('Italian'),
    ('Chinese'),
    ('Mexican'),
    ('Indian'),
    ('French'),
    ('Japanese'),
    ('Korean'),
    ('Thai'),
    ('American'),
    -- tags for dietary options
    ('Vegan'),
    ('Halal'),
    ('Gluten-Free'),
    ('Kosher'),
    -- tags for price range
    ('Inexpensive'),
    ('Moderate'),
    ('Exquisite');

-- Seed data for restaurants
-- Each restaurant includes name, address, rating (1-5), average price, description, and image file extension
INSERT INTO
    "restaurants" (
        "name",
        "address",
        "rating",
        "avg_price",
        "description",
        "file_ext"
    )
VALUES
    (
        'Pasta Palace',
        '123 Noodle St',
        5,
        20,
        'Authentic Italian cuisine with a modern twist.',
        'png'
    ),
    (
        'Sushi Central',
        '456 Fish Ave',
        4,
        30,
        'Fresh sushi and sashimi prepared by expert chefs.',
        'png'
    ),
    (
        'Curry Corner',
        '789 Spice Rd',
        5,
        15,
        'Delicious Indian curries and tandoori dishes.',
        'png'
    ),
    (
        'Taco Town',
        '321 Fiesta Blvd',
        4,
        10,
        'Tasty Mexican street food in a casual setting.',
        'png'
    ),
    (
        'Baguette Bistro',
        '654 Bread Ln',
        5,
        25,
        'Classic French dishes with a cozy atmosphere.',
        'png'
    ),
    (
        'Dragon Wok',
        '88 Commons Ave',
        4,
        12,
        'Affordable Chinese takeout with generous portions.',
        'png'
    ),
    (
        'Kimchi House',
        '200 College Ave',
        5,
        18,
        'Traditional Korean BBQ and authentic flavors.',
        'png'
    ),
    (
        'Spice of Bangkok',
        '155 Cayuga St',
        4,
        16,
        'Authentic Thai dishes with adjustable spice levels.',
        'png'
    ),
    (
        'La Trattoria',
        '301 Stewart Ave',
        5,
        35,
        'Upscale Italian dining with homemade pasta.',
        'png'
    ),
    (
        'The Burger Joint',
        '99 Dryden Rd',
        3,
        8,
        'Quick American burgers and fries for students on the go.',
        'png'
    ),
    (
        'Samosa Palace',
        '176 Fall Creek Dr',
        4,
        11,
        'Indian street food specializing in vegetarian options.',
        'png'
    ),
    (
        'Zen Garden',
        '222 Eddy St',
        5,
        28,
        'Fine Japanese cuisine with traditional tea service.',
        'png'
    );

-- Seed data for restaurant-tag associations
-- Links each restaurant to its appropriate tags (cuisine type, dietary options, price range)
INSERT INTO
    "restaurant_tags" ("restaurant_id", "tag_id")
VALUES
    -- Pasta Palace: Italian, Moderate
    (1, 1),
    (1, 15),
    -- Sushi Central: Japanese, Exquisite
    (2, 6),
    (2, 16),
    -- Curry Corner: Indian, Inexpensive, Vegan
    (3, 4),
    (3, 14),
    (3, 10),
    -- Taco Town: Mexican, Inexpensive
    (4, 3),
    (4, 14),
    -- Baguette Bistro: French, Moderate
    (5, 5),
    (5, 15),
    -- Dragon Wok: Chinese, Inexpensive
    (6, 2),
    (6, 14),
    -- Kimchi House: Korean, Moderate, Halal
    (7, 7),
    (7, 15),
    (7, 11),
    -- Spice of Bangkok: Thai, Moderate, Vegan
    (8, 8),
    (8, 15),
    (8, 10),
    -- La Trattoria: Italian, Exquisite
    (9, 1),
    (9, 16),
    -- The Burger Joint: American, Inexpensive
    (10, 9),
    (10, 14),
    -- Samosa Palace: Indian, Inexpensive, Vegan, Gluten-Free
    (11, 4),
    (11, 14),
    (11, 10),
    (11, 12),
    -- Zen Garden: Japanese, Exquisite
    (12, 6),
    (12, 16);
