-- database: ../test.sqlite
-- Note: Do not delete the line above! It is helpful for testing your init.sql file.
--
-- TODO: entries, tags, and entry_tags table schemas
-- TODO: seed data
DROP TABLE IF EXISTS "course_requests";

CREATE TABLE "restaurants" (
    "id" INTEGER NOT NULL UNIQUE,
    "name" TEXT UNIQUE NOT NULL,
    "address" TEXT UNIQUE NOT NULL,
    "rating" INTEGER,
    "avg_price" INTEGER,
    "description" TEXT,
    PRIMARY KEY ("id" AUTOINCREMENT)
);

DROP TABLE IF EXISTS "tags";

CREATE TABLE "tags" (
    "id" INTEGER NOT NULL UNIQUE,
    "name" TEXT NOT NULL,
    PRIMARY KEY ("id" AUTOINCREMENT)
);

DROP TABLE IF EXISTS "rest_tags";

CREATE TABLE "rest_tags" (
    "id" INTEGER NOT NULL UNIQUE,
    "rest_id" INTEGER NOT NULL,
    "cusine_id" TEXT NOT NULL,
    PRIMARY KEY ("id" AUTOINCREMENT) FOREIGN KEY ("rest_id") REFERENCES "restaurants" ("id") FOREIGN KEY ("cuisine_id") REFERENCES "courses" ("id")
);

-- Note: seed data below are just placeholders generated by ChatGPT 5; it would be nice to have real/inspired places
INSERT INTO "tags" ("name") VALUES
('Italian'),
('Chinese'),
('Mexican'),
('Indian'),
('French'),
('Japanese');

INSERT INTO "restaurants" ("name", "address", "rating", "avg_price", "description") VALUES
('Pasta Palace', '123 Noodle St', 5, 20, 'Authentic Italian cuisine with a modern twist.'),
('Sushi Central', '456 Fish Ave', 4, 30, 'Fresh sushi and sashimi prepared by expert chefs.'),
('Curry Corner', '789 Spice Rd', 5, 15, 'Delicious Indian curries and tandoori dishes.'),
('Taco Town', '321 Fiesta Blvd', 4, 10, 'Tasty Mexican street food in a casual setting.'),
('Baguette Bistro', '654 Bread Ln', 5, 25, 'Classic French dishes with a cozy atmosphere.');

INSERT INTO "rest_tags" ("rest_id", "cusine_id") VALUES
(1, 1),
(2, 6),
(3, 4),
(4, 3),
(5, 5);