-- database: ../test.sqlite
-- Note: Do not delete the line above! It is helpful for testing your init.sql file.
--
-- TODO: entries, tags, and entry_tags table schemas
-- TODO: seed data
DROP TABLE IF EXISTS "course_requests";

CREATE TABLE "restaurants" (
    "id" INTEGER NOT NULL UNIQUE,
    "name" TEXT UNIQUE NOT NULL,
    "address" TEXT UNIQUE NOT NULL,
    "rating" INTEGER,
    "avg_price" INTEGER,
    "description" TEXT,
    PRIMARY KEY ("id" AUTOINCREMENT)
);

DROP TABLE IF EXISTS "tags";

CREATE TABLE "tags" (
    "id" INTEGER NOT NULL UNIQUE,
    "name" TEXT NOT NULL,
    PRIMARY KEY ("id" AUTOINCREMENT)
);

DROP TABLE IF EXISTS "restaurant_tags";

CREATE TABLE "restaurant_tags" (
    "id" INTEGER NOT NULL UNIQUE,
    "restaurant_id" INTEGER NOT NULL,
    "tag_id" INTEGER NOT NULL,
    PRIMARY KEY ("id" AUTOINCREMENT),
    FOREIGN KEY ("restaurant_id") REFERENCES "restaurants" ("id"),
    FOREIGN KEY ("tag_id") REFERENCES "tags" ("id")
);

-- Note: seed data below are just placeholders generated by ChatGPT 5; it would be nice to have real/inspired places
-- tags table consists of a list of cuisine types,
/* several ideas to consider: dietary options, michelin-rated, price range
 Dietary Options: Vegan, Halal, Gluten-Free, Kosher
 Price Range: Affordable, Mid-Price, Fine-Dining */
INSERT INTO
    "tags" ("name")
VALUES
    -- tags for cuisine type
    ('Italian'),
    ('Chinese'),
    ('Mexican'),
    ('Indian'),
    ('French'),
    ('Japanese'),
    ('Korean'),
    ('Thai'),
    ('American'),
    -- tags for dietary options
    ('Vegan'),
    ('Halal'),
    ('Gluten-Free'),
    ('Kosher'),
    -- tags for price range
    ('Inexpensive'),
    ('Moderate'),
    ('Exquisite');

INSERT INTO
    "restaurants" (
        "name",
        "address",
        "rating",
        "avg_price",
        "description"
    )
VALUES
    ('Pasta Palace','123 Noodle St',5,20,'Authentic Italian cuisine with a modern twist.'),
    ('Sushi Central','456 Fish Ave',4,30,'Fresh sushi and sashimi prepared by expert chefs.'),
    ('Curry Corner','789 Spice Rd',5,15,'Delicious Indian curries and tandoori dishes.'),
    ('Taco Town','321 Fiesta Blvd',4,10,'Tasty Mexican street food in a casual setting.'),
    ('Baguette Bistro','654 Bread Ln',5,25,'Classic French dishes with a cozy atmosphere.'),
    ('Dragon Wok','88 Commons Ave',4,12,'Affordable Chinese takeout with generous portions.'),
    ('Kimchi House','200 College Ave',5,18,'Traditional Korean BBQ and authentic flavors.'),
    ('Spice of Bangkok','155 Cayuga St',4,16,'Authentic Thai dishes with adjustable spice levels.'),
    ('La Trattoria','301 Stewart Ave',5,35,'Upscale Italian dining with homemade pasta.'),
    ('The Burger Joint','99 Dryden Rd',3,8,'Quick American burgers and fries for students on the go.'),
    ('Samosa Palace','176 Fall Creek Dr',4,11,'Indian street food specializing in vegetarian options.'),
    ('Zen Garden','222 Eddy St',5,28,'Fine Japanese cuisine with traditional tea service.');

INSERT INTO
    "restaurant_tags" ("restaurant_id", "tag_id")
VALUES
    -- Pasta Palace: Italian, Moderate
    (1, 1),
    (1, 15),
    -- Sushi Central: Japanese, Exquisite
    (2, 6),
    (2, 16),
    -- Curry Corner: Indian, Inexpensive, Vegan
    (3, 4),
    (3, 14),
    (3, 10),
    -- Taco Town: Mexican, Inexpensive
    (4, 3),
    (4, 14),
    -- Baguette Bistro: French, Moderate
    (5, 5),
    (5, 15),
    -- Dragon Wok: Chinese, Inexpensive
    (6, 2),
    (6, 14),
    -- Kimchi House: Korean, Moderate, Halal
    (7, 7),
    (7, 15),
    (7, 11),
    -- Spice of Bangkok: Thai, Moderate, Vegan
    (8, 8),
    (8, 15),
    (8, 10),
    -- La Trattoria: Italian, Exquisite
    (9, 1),
    (9, 16),
    -- The Burger Joint: American, Inexpensive
    (10, 9),
    (10, 14),
    -- Samosa Palace: Indian, Inexpensive, Vegan, Gluten-Free
    (11, 4),
    (11, 14),
    (11, 10),
    (11, 12),
    -- Zen Garden: Japanese, Exquisite
    (12, 6),
    (12, 16);
